version: "3.8"

services:
  mongodb:
    image: mongo:4.4.6
    container_name: testai_mongodb
    restart: unless-stopped
    ports:
      - "27027:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - testai_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: testai_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DOCKER_ENV=true
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - JWT_SECRET=${JWT_SECRET}
      - CLIENT_URL=https://mcp.digital-goods.es
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - testai_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: testai_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=https://mcp.digital-goods.es/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - testai_network

volumes:
  mongodb_data:

networks:
  testai_network:
    driver: bridge
